### ISSUE TITLE
Need to decide JSON configuration

### ISSUE THREAD

**Issue by paylakatel** [CityOfBoston/vizwiz#1]
Need to decide on how we'll set up the JSON this web component will produce so we can properly parse it in the pattern library and future web components.

Did a little research on what other folks are doing:
- [ArcGIS web map specification](https://developers.arcgis.com/web-map-specification/objects/webmap/) has detailed documentation. They have far more options than we need, but below are the high level sections they have that we could have a use for based on features need in our MVP:
     - [applicationProperties](https://developers.arcgis.com/web-map-specification/objects/applicationProperties/) is where they store information about the **Address search** and **Finding user location**
     - [operationalLayers](https://developers.arcgis.com/web-map-specification/objects/operationalLayers/), specifically their notes about [Feature Layers](https://developers.arcgis.com/web-map-specification/objects/featureLayer/), which is what we pull from ArcOnline for data, is where information like the **item url**, **popup information**, and **filters**
     - they also have a high level [table](https://developers.arcgis.com/web-map-specification/objects/table/) object that could be good for future use

- [Carto visjson configuration](https://github.com/CartoDB/cartodb.js/blob/develop/doc/vizjson_format.md) is seemingly less complicated with most of the same inputs as above so may be a good place to start?

Thinking we could probably lift elements from both of these specifications - hoping these docs give us a good place to start.

**Comment by fionawhim** [comment]
This can come organically as we build out configuration and vizwiz.
