### ISSUE TITLE
Raw HTML option for popover template

### ISSUE THREAD

**Issue by fionawhim** [CityOfBoston/vizwiz#21]
For the city council map, we need the following popover template: 

```
<img src="{{Image}}"
  class="cdp-i"
  alt="{{Councilor}}"
  style="margin-bottom: 1rem" />
<div class="ta-c m-v300">
  <div class="cdp-t t--sans t--upper m-t200">{{Councilor}}</div>
  <div class="cdp-st t--subinfo t--g300">District {{DISTRICT}}</div>
</div>
<a href="{{Bio}}"
  class="btn btn--b btn--100 btn--sm">
  Visit webpage
  <span class="a11y--h"> of {{Councillor}}</span>
</a>
```

Currently the data source dialog has a rich text editor for the popover template, so pasting raw HTML ends up showing up literally.

<img width="623" alt="screen shot 2018-03-21 at 4 30 16 pm" src="https://user-images.githubusercontent.com/260837/37735779-70fe4906-2d25-11e8-8aa5-df8a6ea57072.png">

For the city council milestone, the editor should have a way to specify the raw HTML of the popover template.

<img width="529" alt="screen shot 2018-03-21 at 4 32 38 pm" src="https://user-images.githubusercontent.com/260837/37735799-7e0a31be-2d25-11e8-880d-f6c9ab605719.png">

**Comment by paylakatel** [comment]
@coordt just reiterating here what I said in the check-in: we will need the user to be able to enter raw HTML for the city council map/milestone, but ideally the user could choose between a rich text field and raw HTML in future versions.
