### ISSUE TITLE
Discover textarea in order to write JSON to Drupal field

### ISSUE THREAD

**Issue by jimafisk** [CityOfBoston/vizwiz#27]

**Comment by jimafisk** [comment]
VizWiz should be able to figure out which textarea belongs to the same component as itself. That way it can read/write JSON to this field. We need to account for multiple vixwiz fields on the same node.

We can't solely use CSS selectors given the current markup structure:
![vizwiz_markup](https://user-images.githubusercontent.com/5913244/37912365-618e3c92-30e0-11e8-98a9-df0defe1a20e.png)

**Comment by fionawhim** [comment]
Seems to work?
