### ISSUE TITLE
Multiple VizWiz Components on a single page: Inputs values are syncing

### ISSUE THREAD

**Issue by jimafisk** [CityOfBoston/vizwiz#38]
@coordt if I add two VizWiz components to a single page, when I fill out the input fields for the first component, the second component autofills the same values. Here's a gif to illustrate the issue:

![vue_states](https://user-images.githubusercontent.com/5913244/39371584-1ff6b590-4a10-11e8-90eb-c889e24692ee.gif)

**Comment by coordt** [comment]
Fixed with 9fb98a60044e59a371182e4c48240e8a33b6bbf1
